### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by mkchoi212** [ElvinJin/Video-Background-GIF#5]
I've used and implemented your code exactly and so far it works. However, the gif is not filling the entire screen. And for your information, I made a gif that is the exact same size as the one in the demo (iPhone 5) size.

**Comment by mkchoi212** [comment]
I even tried manually putting in the frame for the web view and the view won't even change/move!

**Comment by mkchoi212** [comment]
There just seems to be a grey border around the gif when displayed on iPhone 6 or higher. The same happened when I used the train track gif

**Comment by ElvinJin** [comment]
I think this is the limitation of this approaches to this effect. Since the size and ratio of the Gif are fixed, and we are simply showing the gif in the UIWebView, thus we don't have much control over the gif size. I'm thinking if preparing a HTML template where dynamically change the size parameter, and load this HTML instead of the GIF directly, it could be better?
